baseURL = "https://jackwhiting.co.uk/"
languageCode = "en-gb"
title = "Jack Whiting"
theme = "twentytwenty"
[markup]
  [markup.highlight]
		codeFences = true
		style = "github"
		tabWidth = 2
		lineNos = true
[markup.goldmark.renderer]
	unsafe= true
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
[params]
	description = "Freelance Web Consultant in Nottingham, UK with over 10 years experience working with PHP and JavaScript (Laravel, WordPress, Statamic, Craft, Vue and More). Available for new projects."
	tagline = "Freelance Web Consultant"
	keywords = ["Web", "Developer", "Consultant", "Freelance", "Nottingham", "Svelte", "PHP", "Laravel", "Vue", "JavaScript", "WordPress", "Craft", "Shopify", "Statamic", "WooCommerce", "E-Commerce"]
	twitter = "@jackabox"
	author = "Jack Whiting"
	twitterUrl = "https://twitter.com/jackabox"
	github = "https://github.com/jackabox"
  facebook = "https://www.facebook.com/Jack-Whiting-Development-108935207166374"

