baseURL = "https://jackwhiting.co.uk"
languageCode = "en-gb"
title = "Jack Whiting"
theme = "twentytwenty"
isServer = "false"
[markup]
  [markup.highlight]
		codeFences = true
		style = "github"
		tabWidth = 2
		lineNos = true
[markup.goldmark.renderer]
	unsafe= true
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
